feat: add version and deb build
Co-authored-by: Alessio Perugini <alessio@perugini.xyz>

diff --git a/debian/Dockerfile b/debian/Dockerfile
--- a/debian/Dockerfile
+++ b/debian/Dockerfile
@@ -2,15 +2,22 @@ FROM golang:1.24.2 AS go
 
 ARG BINARY_NAME
 RUN test -n "${BINARY_NAME}" || (echo "Error: BINARY_NAME is not set" && exit 1)
+ARG VERSION
+RUN test -n "${VERSION}" || (echo "Error: VERSION is not set" && exit 1)
+ARG ARCH
+RUN test -n "${ARCH}" || (echo "Error: ARCH is not set" && exit 1)
 
 COPY . /app
 WORKDIR /app
-RUN GOOS=linux go build -o ${BINARY_NAME} ./cmd/${BINARY_NAME}
+RUN GOOS=linux GOARCH=${ARCH} go build -ldflags "-X 'main.Version=${VERSION}'" -o ${BINARY_NAME} ./cmd/${BINARY_NAME}
 
 FROM debian:bookworm AS debian
 
-ARG VERSION="1.0.0"
+ARG VERSION
+RUN test -n "${VERSION}" || (echo "Error: VERSION is not set" && exit 1)
 ARG REVISION="1"
+ARG ARCH
+RUN test -n "${ARCH}" || (echo "Error: ARCH is not set" && exit 1)
 ARG DEB_NAME
 RUN test -n "${DEB_NAME}" || (echo "Error: DEB_NAME is not set" && exit 1)
 ARG BINARY_NAME
@@ -21,9 +28,10 @@ RUN apt-get update && apt-get install -y sed
 COPY ./debian/${DEB_NAME} /${DEB_NAME}/
 COPY --from=go /app/${BINARY_NAME} /${DEB_NAME}/usr/bin/${BINARY_NAME}
 
-RUN sed -i "s/ARCH/$(dpkg --print-architecture)/" /${DEB_NAME}/DEBIAN/control && \
+RUN sed -i "s/ARCH/${ARCH}/" /${DEB_NAME}/DEBIAN/control && \
+    sed -i "s/VERSION/${VERSION}/" /${DEB_NAME}/DEBIAN/control && \
     dpkg-deb --build --root-owner-group /${DEB_NAME} &&\
-    mv /${DEB_NAME}.deb "/${DEB_NAME}_${VERSION}-${REVISION}_$(dpkg --print-architecture).deb"
+    mv /${DEB_NAME}.deb "/${DEB_NAME}_${VERSION}-${REVISION}_${ARCH}.deb"
 
 FROM scratch
 
